### ISSUE TITLE
Python Fails to Serialize FeatureFlag Object

### ISSUE THREAD

**Issue by leibylucw** [Prime-Access-Consulting/nvda-at-automation#24]
This occurs when issuing a `vendor:settings.getSupportedSettings` command. The following error is thrown: `TypeError: Object of type FeatureFlag is not JSON serializable`

**Comment by jkva** [comment]
[FeatureFlag](https://github.com/nvaccess/nvda/blob/9e37ced7c07a09a5513c4952d9756eb87524c1ef/source/config/featureFlag.py) is a newer addition to NVDA; the add-on will need to subclass `json.JSONEncoder` and implement custom serialisation.
