### ISSUE TITLE
API incompatibility with NVDA 2023.1.0.27913?

### ISSUE THREAD

**Issue by gnarf** [Prime-Access-Consulting/nvda-at-automation#33]
Following the instructions provided, I've put the plugin into a copy of nvda-portable 2023.1.0.27913 in the correct location, but the `localhost:8765` port never opens.  I found this in the nvda logs which seems to be complaining that the addon is incompatible.

```
DEBUG - addonHandler._getAvailableAddonsFromPath (12:39:40.306) - MainThread (35568):
Listing add-ons from F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.1.0.27913\userConfig\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (12:39:40.306) - MainThread (35568):
Loading add-on from F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.1.0.27913\userConfig\addons\NVDAPlugin
DEBUG - addonHandler._getAvailableAddonsFromPath (12:39:40.306) - MainThread (35568):
Found add-on CommandSocket - 1.0. Requires API: (2022, 1, 0). Last-tested API: (2022, 3, 0)
DEBUGWARNING - addonHandler._getAvailableAddonsFromPath (12:39:40.306) - MainThread (35568):
Add-on CommandSocket is considered incompatible
```

**Comment by jscholes** [comment]
@gnarf This should now be addressed, in pure add-on manifest compatibility terms.  The add-on should be accepted by NVDA, but let us know if you run into any compatibility issues within its actual functionality.

**Comment by gnarf** [comment]
I tried updating the manifest for 2023.2 (which released since this last message) and the addon doesn't seem to properly start up and listen to the 8765 port - here is the `nvda.exe --debug-logging` output from an attempt:

<details><pre>
DEBUG - __main__ (15:23:31.865) - MainThread (9380):
Provided arguments: ['--debug-logging']
INFO - __main__ (15:23:31.865) - MainThread (9380):
Starting NVDA version 2023.2
DEBUG - __main__ (15:23:31.865) - MainThread (9380):
Debug level logging enabled
DEBUG - core.main (15:23:33.493) - MainThread (9380):
Core starting
DEBUG - NVDAState._configInLocalAppDataEnabled (15:23:33.493) - MainThread (9380):
Installed user config is not in local app data
INFO - core.main (15:23:33.495) - MainThread (9380):
Config dir: F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig
DEBUG - core.main (15:23:33.495) - MainThread (9380):
loading config
INFO - config.ConfigManager._loadConfig (15:23:33.498) - MainThread (9380):
Loading config: F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\nvda.ini
DEBUG - config.profileUpgrader.upgrade (15:23:33.501) - MainThread (9380):
Current config schema version: 10, latest: 10
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.502) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: ReviewRoutingMovesSystemCaretFlag, behaviorOfDefault: NEVER
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.502) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: ReviewRoutingMovesSystemCaretFlag, behaviorOfDefault: NEVER
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: DISABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.503) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: DISABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.504) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.504) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: ENABLED
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.504) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: ParagraphNavigationFlag, behaviorOfDefault: APPLICATION
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.504) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: ParagraphNavigationFlag, behaviorOfDefault: APPLICATION
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.505) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.505) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
DEBUG - fileUtils.FaultTolerantFile (15:23:33.505) - MainThread (9380):
F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\nvda.iniswipwmt6.tmp
INFO - config.ConfigManager._loadConfig (15:23:33.513) - MainThread (9380):
Config loaded (after upgrade, and in the state it will be used by NVDA):
{'schemaVersion': '10', 'upgrade': {}, 'update': {'allowUsageStats': 'False', 'askedAllowUsageStats': 'True'}, 'development': {}, 'general': {'showWelcomeDialogAtStartup': 'True'}, 'speech': {'synth': 'oneCore', 'oneCore': {'voice': 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Speech_OneCore\\Voices\\Tokens\\MSTTS_V110_enUS_DavidM', 'rate': '50', 'rateBoost': 'False', 'pitch': '50', 'volume': '100'}}, 'braille': {'display': 'auto', 'noBraille': {}}, 'vision': {'NVDAHighlighter': {'highlightFocus': 'False', 'highlightNavigator': 'False', 'highlightBrowseMode': 'False'}, 'screenCurtain': {'warnOnLoad': 'True', 'playToggleSounds': 'True'}}, 'keyboard': {'keyboardLayout': 'desktop', 'NVDAModifierKeys': '6'}}
DEBUG - core.main (15:23:33.513) - MainThread (9380):
setting language to Windows
DEBUGWARNING - languageHandler._createGettextTranslation (15:23:33.513) - MainThread (9380):
couldn't set the translation service locale to en_US
DEBUG - languageHandler.setLocale (15:23:33.513) - MainThread (9380):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (15:23:33.515) - MainThread (9380):
set python locale to English_United States.1252
DEBUG - core.main (15:23:33.605) - MainThread (9380):
Initializing NVDAHelper
DEBUG - NVDAHelper._RemoteLoader.__init__ (15:23:33.612) - MainThread (9380):
Starting F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\lib64\2023.2\nvdaHelperRemoteLoader.exe
DEBUG - core.main (15:23:33.615) - MainThread (9380):
initializing nvwave
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:33.615) - MainThread (9380):
Validating feature flag: DEFAULT, optionsEnum: BoolFlag, behaviorOfDefault: DISABLED
INFO - core.main (15:23:33.649) - MainThread (9380):
Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64
INFO - core.main (15:23:33.649) - MainThread (9380):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (15:23:33.649) - MainThread (9380):
Using comtypes version 1.1.11
INFO - core.main (15:23:33.649) - MainThread (9380):
Using configobj version 5.1.0 with validate version 1.0.1
DEBUG - core.main (15:23:33.649) - MainThread (9380):
Initializing add-ons system
DEBUG - _addonStore.dataManager.initialize (15:23:33.682) - MainThread (9380):
initializing addonStore data manager
DEBUG - addonHandler._getAvailableAddonsFromPath (15:23:33.687) - MainThread (9380):
Listing add-ons from F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\addons
DEBUG - addonHandler._getAvailableAddonsFromPath (15:23:33.687) - MainThread (9380):
Loading add-on from F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\addons\NVDAPlugin
DEBUG - addonHandler._getAvailableAddonsFromPath (15:23:33.687) - MainThread (9380):
Found add-on CommandSocket - 1.0. Requires API: (2022, 1, 0). Last-tested API: (2023, 2, 0)
DEBUG - core.main (15:23:33.688) - MainThread (9380):
Initializing appModule Handler
DEBUG - core.main (15:23:33.688) - MainThread (9380):
initializing background i/o
DEBUG - core.main (15:23:33.688) - MainThread (9380):
Initializing background braille display detection
DEBUG - core.main (15:23:33.689) - MainThread (9380):
Initializing tones
DEBUG - core.main (15:23:33.692) - MainThread (9380):
Speech Dictionary processing
DEBUG - speechDictHandler.SpeechDict.load (15:23:33.692) - MainThread (9380):
Loading speech dictionary 'F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\speechDicts\default.dic'...
DEBUG - speechDictHandler.SpeechDict.load (15:23:33.692) - MainThread (9380):
file 'F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\speechDicts\default.dic' not found.
DEBUG - speechDictHandler.SpeechDict.load (15:23:33.692) - MainThread (9380):
Loading speech dictionary 'F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\builtin.dic'...
DEBUG - speechDictHandler.SpeechDict.load (15:23:33.693) - MainThread (9380):
3 loaded records.
DEBUG - core.main (15:23:33.693) - MainThread (9380):
Initializing speech
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (15:23:33.694) - MainThread (9380):
registering pre_configSave action: <class 'synthDrivers.oneCore.OneCoreSynthDriver'>
INFO - NVDAHelperLocal (15:23:33.696) - MainThread (9380):
Thread 9380, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_initialize, 215:
ocSpeech_initialize

INFO - NVDAHelperLocal (15:23:33.696) - MainThread (9380):
Thread 9380, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::activate, 89:
Activating

INFO - NVDAHelperLocal (15:23:33.727) - MainThread (9380):
Thread 9380, build\x86\localWin10\oneCoreSpeech.cpp, preventEndUtteranceSilence_, 443:
AppendedSilence supported

DEBUG - speechDictHandler.SpeechDict.load (15:23:33.731) - MainThread (9380):
Loading speech dictionary 'F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft David.dic'...
DEBUG - speechDictHandler.SpeechDict.load (15:23:33.731) - MainThread (9380):
file 'F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\speechDicts\voiceDicts.v1\oneCore\oneCore-Microsoft David.dic' not found.
DEBUG - synthDriverHandler.SynthDriver.loadSettings (15:23:33.731) - MainThread (9380):
Loaded settings for SynthDriver oneCore
INFO - synthDriverHandler.setSynth (15:23:33.731) - MainThread (9380):
Loaded synthDriver oneCore
DEBUG - speech.sayAll.initialize (15:23:33.731) - MainThread (9380):
Initializing sayAllHandler
DEBUG - core.main (15:23:33.734) - MainThread (9380):
Initializing MathPlayer
WARNING - mathPres.initialize (15:23:33.737) - MainThread (9380):
MathPlayer 4 not available
INFO - core.main (15:23:33.737) - MainThread (9380):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
DEBUG - core.main (15:23:33.738) - MainThread (9380):
Initializing braille input
INFO - brailleInput.initialize (15:23:33.739) - MainThread (9380):
Braille input initialized
DEBUG - core.main (15:23:33.739) - MainThread (9380):
Initializing braille
INFO - braille.initialize (15:23:33.739) - MainThread (9380):
Using liblouis version 3.25.0
INFO - braille.initialize (15:23:33.739) - MainThread (9380):
Using pySerial version 3.5
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (15:23:33.739) - MainThread (9380):
registering pre_configSave action: <class 'brailleDisplayDrivers.noBraille.BrailleDisplayDriver'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:23:33.741) - MainThread (9380):
loading braille noBraille
INFO - braille.BrailleHandler._setDisplay (15:23:33.741) - MainThread (9380):
Loaded braille display driver 'noBraille', current display has 0 cells.
DEBUG - core.main (15:23:33.741) - MainThread (9380):
Initializing vision
DEBUG - core.main (15:23:33.742) - MainThread (9380):
Initializing displayModel
DEBUG - core.main (15:23:33.742) - MainThread (9380):
Initializing GUI
DEBUG - windowUtils._rawWindowProc (15:23:33.758) - MainThread (9380):
CustomWindow rawWindowProc called for unknown window 9636314
DEBUG - windowUtils._rawWindowProc (15:23:33.758) - MainThread (9380):
CustomWindow rawWindowProc called for unknown window 9636314
DEBUG - windowUtils._rawWindowProc (15:23:33.758) - MainThread (9380):
CustomWindow rawWindowProc called for unknown window 9636314
DEBUG - windowUtils._rawWindowProc (15:23:33.758) - MainThread (9380):
CustomWindow rawWindowProc called for unknown window 9636314
DEBUG - languageHandler.setLocale (15:23:33.766) - MainThread (9380):
Win32 locale string from locale code is English_United States.1252
DEBUG - languageHandler._setPythonLocale (15:23:33.766) - MainThread (9380):
set python locale to English_United States.1252
DEBUG - core.main (15:23:33.766) - MainThread (9380):
Initializing garbageHandler
DEBUG - core.main (15:23:33.772) - MainThread (9380):
initializing Java Access Bridge support
INFO - core.main (15:23:33.838) - MainThread (9380):
Java Access Bridge support initialized
DEBUG - core.main (15:23:33.839) - MainThread (9380):
Initializing legacy winConsole support
DEBUG - core.main (15:23:33.871) - MainThread (9380):
Initializing UIA support
INFO - UIAHandler.UIAHandler.MTAThreadFunc (15:23:33.876) - UIAHandler.UIAHandler.MTAThread (29484):
UIAutomation: IUIAutomation6
DEBUG - core.main (15:23:34.325) - MainThread (9380):
Initializing IAccessible support
DEBUG - core.main (15:23:34.326) - MainThread (9380):
Initializing input core
DEBUGWARNING - inputCore.InputManager.loadLocaleGestureMap (15:23:34.326) - MainThread (9380):
No locale gesture map for language en
DEBUGWARNING - inputCore.InputManager.loadUserGestureMap (15:23:34.326) - MainThread (9380):
No user gesture map
DEBUG - core.main (15:23:34.326) - MainThread (9380):
Initializing keyboard handler
DEBUG - core.main (15:23:34.327) - MainThread (9380):
initializing mouse handler
DEBUG - core.main (15:23:34.345) - MainThread (9380):
Initializing touchHandler
DEBUGWARNING - touchHandler.touchSupported (15:23:34.345) - MainThread (9380):
Touch only supported on installed copies
DEBUG - core.main (15:23:34.345) - MainThread (9380):
Initializing global plugin handler
DEBUG - core.main (15:23:34.346) - MainThread (9380):
Initializing core pump
DEBUG - core.main (15:23:34.347) - MainThread (9380):
Initializing watchdog
DEBUG - core.main (15:23:34.347) - MainThread (9380):
initializing updateCheck
INFO - core.main (15:23:34.348) - MainThread (9380):
NVDA initialized
DEBUG - core.main (15:23:34.348) - MainThread (9380):
entering wx application main loop
DEBUG - gui.contextHelp.bindHelpEvent (15:23:34.353) - MainThread (9380):
Did context help binding for WelcomeDialog
DEBUG - config.getStartAfterLogon (15:23:34.367) - MainThread (9380):
NVDA is not set to start after logon
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (15:23:34.442) - MainThread (9380):
registering pre_configSave action: <class 'visionEnhancementProviders.NVDAHighlighter.NVDAHighlighterSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:23:34.444) - MainThread (9380):
loading vision NVDAHighlighter
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:23:34.445) - MainThread (9380):
Loaded settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._registerConfigSaveAction (15:23:34.446) - MainThread (9380):
registering pre_configSave action: <class 'visionEnhancementProviders.screenCurtain.ScreenCurtainSettings'>
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:23:34.448) - MainThread (9380):
loading vision screenCurtain
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._loadSpecificSettings (15:23:34.448) - MainThread (9380):
Loaded settings for ScreenCurtainSettings
DEBUG - core._doPostNvdaStartupAction (15:23:34.449) - MainThread (9380):
Notify of postNvdaStartup action
IO - speech.speech.speak (15:23:34.462) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Welcome to NVDA', 'dialog', 'Welcome to NVDA!\nMost commands for controlling NVDA require you to hold down the NVDA key while pressing other keys.\nBy default, the numpad Insert and main Insert keys may both be used as the NVDA key.\nYou can also configure NVDA to use the CapsLock as the NVDA key.\nPress NVDA+n at any time to activate the NVDA menu.\nFrom this menu, you can configure NVDA, get help and access other NVDA functions.', CancellableSpeech (still valid)]
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (15:23:34.462) - MainThread (9380):
No CLDR data for locale en_US
DEBUGWARNING - characterProcessing._getSpeechSymbolsForLocale (15:23:34.462) - MainThread (9380):
No symbol data for locale en_US
IO - speech.speech.speak (15:23:34.524) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Options', 'grouping', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:34.526) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Keyboard layout:', 'combo box', 'desktop', 'collapsed', 'Alt+k', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:35.787) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Welcome to NVDA Welcome to NVDA!\nMost commands for controlling NVDA require you to hold down the NVDA key while pressing other keys.\nBy default, the numpad Insert and main Insert keys may both be used as the NVDA key.\nYou can also configure NVDA to use the CapsLock as the NVDA key.\nPress NVDA+n at any time to activate the NVDA menu.\nFrom this menu, you can configure NVDA, get help and access other NVDA functions.']
IO - speech.speech.speak (15:23:35.803) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'OK']
IO - speech.speech.speak (15:23:36.140) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'OK', 'button', 'pressed', CancellableSpeech (still valid)]
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:36.219) - MainThread (9380):
Saved settings for OneCoreSynthDriver
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:36.219) - MainThread (9380):
Saved settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:36.219) - MainThread (9380):
Saved settings for ScreenCurtainSettings
DEBUG - fileUtils.FaultTolerantFile (15:23:36.219) - MainThread (9380):
F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\nvda.inierrnc9lw.tmp
INFO - config.ConfigManager.save (15:23:36.227) - MainThread (9380):
Base configuration saved
IO - speech.speech.speak (15:23:36.295) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'nvda.log - aria-at - Visual Studio Code', CancellableSpeech (still valid)]
DEBUG - config.featureFlag._validateConfig_featureFlag (15:23:36.382) - Dummy-1 (22232):
Validating feature flag: DEFAULT, optionsEnum: WindowsTerminalStrategyFlag, behaviorOfDefault: DIFFING
IO - speech.speech.speak (15:23:36.486) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'nvda.log - aria-at - Visual Studio Code', 'document', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:36.487) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'application', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets (15:23:36.493) - MainThread (9380):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 337, in _getLineOffsets
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speech.speak (15:23:36.495) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Terminal 4, nvda Run the command: Toggle Screen Reader Accessibility Mode for an optimized screen reader experience Use Alt+F1 for terminal accessibility help', 'edit', CancellableSpeech (still valid), 'blank']
IO - speech.speech.speak (15:23:37.489) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Spaces: 4']
IO - speech.speech.speak (15:23:37.516) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Spaces: 4']
IO - speech.speech.speak (15:23:37.683) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Notification Chevron']
IO - speech.speech.speak (15:23:37.719) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Taskbar']
IO - speech.speech.speak (15:23:37.875) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Notification Chevron']
DEBUGWARNING - NVDAObjects.IAccessible.IAccessible._get_IAccessibleRole (15:23:38.078) - MainThread (9380):
accRole failed: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speech.speak (15:23:38.110) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Taskbar', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:38.186) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Notification Overflow', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:38.484) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'NVDA']
IO - speech.speech.speak (15:23:39.055) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'NVDA', 'menu', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:39.273) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Exit', 'x', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:39.281) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Exit']
IO - speech.speech.speak (15:23:39.696) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Exit NVDA', 'dialog', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:39.697) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'What would you like to do?', 'combo box', 'Exit', 'collapsed', 'Alt+d', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:40.084) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Overflow Notification Area']
IO - speech.speech.speak (15:23:40.112) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Battle.net']
IO - speech.speech.speak (15:23:40.387) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Exit NVDA']
IO - speech.speech.speak (15:23:40.532) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Cancel']
IO - speech.speech.speak (15:23:40.557) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'OK']
IO - speech.speech.speak (15:23:40.763) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'OK', 'button', 'pressed', CancellableSpeech (still valid)]
DEBUG - core.triggerNVDAExit (15:23:40.868) - MainThread (9380):
_doShutdown has been queued
DEBUG - core._terminate (15:23:40.881) - MainThread (9380):
Terminating updateCheck
DEBUG - core._terminate (15:23:40.881) - MainThread (9380):
Terminating watchdog
DEBUG - core._terminate (15:23:40.881) - MainThread (9380):
Terminating globalPluginHandler
DEBUG - core._closeAllWindows (15:23:40.881) - MainThread (9380):
destroying system tray icon and menu
DEBUG - core._closeAllWindows (15:23:40.887) - MainThread (9380):
closing window <gui.startupDialogs.WelcomeDialog object at 0x09446530> during exit process
DEBUG - core._closeAllWindows (15:23:40.888) - MainThread (9380):
closing window <gui.exit.ExitDialog object at 0x0C911260> during exit process
DEBUG - core._closeAllWindows (15:23:40.909) - MainThread (9380):
destroying main frame during exit process
IO - speech.speech.speak (15:23:40.977) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'nvda.log - aria-at - Visual Studio Code', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:41.136) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'nvda.log - aria-at - Visual Studio Code', 'document', CancellableSpeech (still valid)]
IO - speech.speech.speak (15:23:41.138) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'application', CancellableSpeech (still valid)]
DEBUGWARNING - NVDAObjects.IAccessible.IA2TextTextInfo._getLineOffsets (15:23:41.141) - MainThread (9380):
IAccessibleText::textAtOffset failed
Traceback (most recent call last):
  File "NVDAObjects\IAccessible\__init__.pyc", line 337, in _getLineOffsets
  File "comtypes\__init__.pyc", line 856, in __call__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'The parameter is incorrect.', (None, None, None, 0, None))
IO - speech.speech.speak (15:23:41.143) - MainThread (9380):
Speaking [LangChangeCommand ('en_US'), 'Terminal 4, nvda Run the command: Toggle Screen Reader Accessibility Mode for an optimized screen reader experience Use Alt+F1 for terminal accessibility help', 'edit', CancellableSpeech (still valid), 'blank']
INFO - core.main (15:23:41.158) - MainThread (9380):
Exiting
DEBUG - core.triggerNVDAExit (15:23:41.158) - MainThread (9380):
NVDA has already been triggered to exit safely.
DEBUG - core._terminate (15:23:41.158) - MainThread (9380):
Terminating gui
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:41.159) - MainThread (9380):
Saved settings for OneCoreSynthDriver
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:41.159) - MainThread (9380):
Saved settings for NVDAHighlighterSettings
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:41.159) - MainThread (9380):
Saved settings for ScreenCurtainSettings
DEBUG - fileUtils.FaultTolerantFile (15:23:41.159) - MainThread (9380):
F:\Code\aria-at\gh-actions-testing\nvda-portable\2023.2.0.29051\userConfig\nvda.inir2ms5ue2.tmp
INFO - config.ConfigManager.save (15:23:41.166) - MainThread (9380):
Base configuration saved
DEBUG - core._doLoseFocus (15:23:41.167) - MainThread (9380):
calling lose focus on object with focus
DEBUG - core._terminate (15:23:41.170) - MainThread (9380):
Terminating treeInterceptorHandler
DEBUG - core._terminate (15:23:41.170) - MainThread (9380):
Terminating IAccessible support
DEBUG - core._terminate (15:23:41.170) - MainThread (9380):
Terminating UIA support
DEBUGWARNING - UIAHandler.UIAHandler.terminate (15:23:41.370) - MainThread (9380):
Timeout or error while waiting for UIAHandler MTA thread
DEBUG - core._terminate (15:23:41.370) - MainThread (9380):
Terminating Legacy winConsole support
DEBUG - core._terminate (15:23:41.370) - MainThread (9380):
Terminating Java Access Bridge support
DEBUG - core._terminate (15:23:41.371) - MainThread (9380):
Terminating app module handler
DEBUG - core._terminate (15:23:41.371) - MainThread (9380):
Terminating tones
DEBUG - core._terminate (15:23:41.372) - MainThread (9380):
Terminating touchHandler
DEBUG - core._terminate (15:23:41.372) - MainThread (9380):
Terminating keyboard handler
DEBUG - core._terminate (15:23:41.372) - MainThread (9380):
Terminating mouseHandler
DEBUG - core._terminate (15:23:41.373) - MainThread (9380):
Terminating inputCore
DEBUG - core._terminate (15:23:41.373) - MainThread (9380):
Terminating vision
DEBUG - core._terminate (15:23:41.373) - MainThread (9380):
Terminating brailleInput
DEBUG - core._terminate (15:23:41.373) - MainThread (9380):
Terminating braille
DEBUG - core._terminate (15:23:41.373) - MainThread (9380):
Terminating speech
DEBUG - autoSettingsUtils.autoSettings.AutoSettings._saveSpecificSettings (15:23:41.373) - MainThread (9380):
Saved settings for OneCoreSynthDriver
INFO - NVDAHelperLocal (15:23:41.374) - MainThread (9380):
Thread 9380, build\x86\localWin10\oneCoreSpeech.cpp, ocSpeech_terminate, 236:
ocSpeech_terminate, token: 03E4CE84

INFO - NVDAHelperLocal (15:23:41.374) - MainThread (9380):
Thread 9380, build\x86\localWin10\oneCoreSpeech.cpp, OcSpeechState::terminate, 106:
Terminating

DEBUG - core._terminate (15:23:41.376) - MainThread (9380):
Terminating bdDetect
DEBUG - core._terminate (15:23:41.376) - MainThread (9380):
Terminating hwIo
DEBUG - core._terminate (15:23:41.376) - MainThread (9380):
Terminating addonHandler
DEBUG - core._terminate (15:23:41.376) - MainThread (9380):
Terminating garbageHandler
DEBUG - core._terminate (15:23:42.421) - MainThread (9380):
Terminating NVDAHelper
DEBUG - core.main (15:23:42.424) - MainThread (9380):
core done
INFO - __main__ (15:23:44.180) - MainThread (9380):
NVDA exit
```
</pre></details>
