### ISSUE TITLE
Trouble with press keys, not sure what I'm missing or doing incorrectly.

### ISSUE THREAD

**Issue by gnarf** [Prime-Access-Consulting/nvda-at-automation#35]
Neither `space` nor `SPACE` seem to be valid keys for press keys?

Sending the command:
```
{"id":"0","type":"command","method":"interaction.pressKeys","params":{"keys":["space"]}}
```

Two issues arise... 
* [ ] The server replies with a "positive" result, not indicating there was an error (even though the press keys fails)
* [x] The key is not pressed

Log from nvda.log:
```
WARNING - stdout (17:37:33.213) - Thread-1 (10748):
invalid key 'space'
WARNING - stdout (17:37:33.213) - Thread-1 (10748):
error executing gesture None: could not create gesture using "space"
```

I'm sure I'm just missing something with regards to how these keys are supposed to be passed in as params, but I can't figure out what it is.

**Comment by jscholes** [comment]
@gnarf Instead of key names, please try the keycodes from:

https://github.com/SeleniumHQ/selenium/blob/63e8543a39778a5fa65ff2149597066abdbb9abb/py/selenium/webdriver/common/keys.py

**Comment by gnarf** [comment]
thanks for the pointer, I even saw this table of conversions in the python when I was trying to figure it out myself, but thought that it was converting from "SPACE" -> the \ue0 code rather than trying to read from the \ue0 code!

The first checkbox in the issue still feels important though, I would expect an "error" to be given back to the response on the websocket protocol.

**Comment by gnarf** [comment]
The `\ue0xx` pointer got me past the "key doesn't get pressed" part, but the error handling might want it's own issue for tracking.

**Comment by jscholes** [comment]
@gnarf I agree!  Closing this in favour of https://github.com/Prime-Access-Consulting/nvda-at-automation/issues/36.
