### ISSUE TITLE
Command "id" property should be uint not string

### ISSUE THREAD

**Issue by gnarf** [Prime-Access-Consulting/nvda-at-automation#40]
While going through and reviewing the changes I was making to get everything playing together on the automation testing, it was brought to my attention that [`id` is defined as an unsigned integer for Command, CommandResponse, and (generally) ErrorResponse.](https://w3c.github.io/at-driver/#protocol-definition).

**Comment by gnarf** [comment]
This issue feels a bit "blocker" level because I really don't want to land the string conversion I needed to work with this in the w3c/aria-at-automation-harness repo main branch.  I can continue to work around it in a temporary branch in the meantime, but it would be nice to not need to use a "special" branch to test against this driver.

**Comment by jscholes** [comment]
@gnarf Unfortunately, I don't think we can currently commit to addressing this in the sort of timeline you're after.  However, we'd be happy to accept and review a PR if that would speed things up.

**Comment by gnarf** [comment]
No problems, thanks for the again very quick reply.  I'll see if I can make enough sense of golang to make this change (or find a co-worker who can.)
